name: Non production environments pipeline

on:
   workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${{ github.sha }}"
  
jobs:
  # build:
  #   runs-on: self-hosted
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
      
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_PASSWORD }}

  #   - name: Build and push
  #     uses: docker/build-push-action@v6
  #     with:
  #       push: true
  #       tags: ${{env.IMAGE_NAME}}

  # test:
  #   runs-on: self-hosted
  #   needs: build
  #   steps: 
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         image: ${{ env.IMAGE_NAME }}
  #         run: pytest .

  # scan:
  #   runs-on: self-hosted
  #   needs: test
  #   steps:
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@0.20.0
  #       with:
  #         image-ref: ${{ env.IMAGE_NAME }}
  #         format: 'table'
  #         exit-code: '1'
  #         severity: 'CRITICAL,HIGH,MEDIUM'
  #       env:
  #         TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy_dev:
    runs-on: self-hosted
    container:
      image: dellnoantechnp/git-yq:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: yoav7000/gitops-devops-project
        token: ${{ secrets.GITOPS_REPO_TOKEN }}

    - name: Mark directory as safe
      run: |
        git config --global --add safe.directory $(pwd)

    - name: Change value in YAML file
      run: |
        yq e '.image.tag = "cba1df93eb833a5cf5721320d68fd1839dfc79ea"' -i environments/dev/values/microservice-devops-values.yaml

    - name: Commit changes
      run: |
        git status
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add environments/dev/values/microservice-devops-values.yaml
        git commit -m "Update tag in values file"
        git push