name: Non production environments pipeline

on:
   workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      app_name: ${{inputs.app_name}}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  harta:
    runs-on: self-hosted
    needs: build
    steps:
      - name: harta
        run: echo ${{ needs.build.outputs.image_name }}
  test:
    needs: build
    uses: ./.github/workflows/pytest.yaml
    with: 
      image_name: ${{ needs.build.outputs.image_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}