name: Non production environments pipeline

on:
   workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      gitops_repo:
        required: true
        type: string
      gitops_values_path:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${{ github.sha }}"
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}

  # test:
  #   runs-on: self-hosted
  #   needs: build
  #   steps: 
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         image: ${{ env.IMAGE_NAME }}
  #         run: pytest .

  # scan:
  #   runs-on: self-hosted
  #   needs: test
  #   steps:
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@0.20.0
  #       with:
  #         image-ref: ${{ env.IMAGE_NAME }}
  #         format: 'table'
  #         exit-code: '1'
  #         severity: 'CRITICAL,HIGH'
  #       env:
  #         TRIVY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #         TRIVY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy_dev:
    runs-on: self-hosted
    environment: dev
    needs: build #scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.gitops_repo }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}

    - name: Set values file path variable based on the environment 
      run: |
        echo "VALUES_PATH = $(echo '${{ inputs.gitops_values_path }}' | sed 's/{ENV_NAME}/dev/')" >> $GITHUB_ENV

    - name: Change value in YAML file
      uses: mikefarah/yq@v4.44.3
      with:
        cmd: yq e '.image.tag = "${{ github.sha }}"' -i $VALUES_PATH

    - name: Commit changes to gitops repo
      run: |
        git status
        git config --local user.name "yoav7000"
        git config --local user.email "actions@github.com"
        git add $VALUES_PATH
        git commit -m "Update dev ${{ inputs.app_name }} image tag to ${{ github.sha }}"
        git push

  deploy_staging:
    runs-on: self-hosted
    environment: staging
    needs: deploy_dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.gitops_repo }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}

    - name: Change value in YAML file
      uses: mikefarah/yq@v4.44.3
      with:
        cmd: yq e '.image.tag = "${{ github.sha }}"' -i ${{ inputs.gitops_values_path }}

    - name: Commit changes to gitops repo
      run: |
        git status
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add ${{ inputs.gitops_values_path }}
        git commit -m "Update dev ${{ inputs.app_name }} image tag to ${{ github.sha }}"
        git push