name: production pipeline

on:
   workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      gitops_repo:
        required: true
        type: string
      gitops_values_path:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true

env:
  NEW_IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${{ github.ref_name }}"

jobs:
  tag_and_push_image:
    runs-on: self-hosted
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Rename image and push
      run: |
        LAST_IMAGE_TAG=$(git log -1 ${{ github.sha }}^2 --pretty=format:"%H") # Get the image tag based on commit sha
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${LAST_IMAGE_TAG}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${LAST_IMAGE_TAG} ${{ env.NEW_IMAGE_NAME }}
        docker push  ${{ env.NEW_IMAGE_NAME }}
