name: production pipeline

on:
   workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      gitops_repo:
        required: true
        type: string
      gitops_values_path:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GITOPS_REPO_TOKEN:
        required: true

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${{ github.ref_name }}"
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}

  deploy_prod:
    runs-on: self-hosted
    environment: production
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.gitops_repo }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}

    - name: Set values file path variable based on the environment 
      run: |
        echo "VALUES_PATH=$(echo '${{ inputs.gitops_values_path }}' | sed 's/{ENV_NAME}/prod/')" >> $GITHUB_ENV

    - name: Change value in YAML file
      uses: mikefarah/yq@v4.44.3
      with:
        cmd: yq e '.image.tag = "${{ github.ref_name }}"' -i $VALUES_PATH

    - name: Commit changes to gitops repo
      run: |
        git status
        git config --local user.name "Github Actions"
        git config --local user.email "actions@github.com"
        git add $VALUES_PATH
        git commit -m "Update prod ${{ inputs.app_name }} image tag to ${{ github.ref_name }}"
        git push
